services:
  helix_bridge:
    image: ghcr.io/0xconnorrhodes/helix-data-bridge:latest
    hostname: helix_bridge
    container_name: helix_bridge
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changeme
    # volumes:
    #   - ./.env:/app/.env # contents: VERKADA_API_KEY="mykey"
    #   - ./devices_config.csv:/app/devices_config.csv
    #   - ./event_types_config.csv:/app/event_types_config.csv